rolwiki/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from wiki import urls as wikiurl

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(wikiurl)),
]

wiki/urls.py
from django.conf.urls import url
from .views import (
    IndexView, ParaHumanDetailView, EntranceDetailView,
    EntrancesListView,
)


urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(), name='index'
    ),
    url(
        r'^entrances/$',
        EntrancesListView.as_view(), name='entrances'
    ),
    url(
        r'^(?P<pk>[0-9]+)/$',
        ParaHumanDetailView.as_view(), name='parahuman'
    ),
    url(
        r'^entrance/(?P<pk>[0-9]+)/$',
        EntranceDetailView.as_view(), name='entrance'
    ),
]

wiki/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class ParaHuman(models.Model):

    cape_name = models.CharField(max_length=200)
    description = models.TextField()

    class Meta:
        verbose_name = "ParaHuman"
        verbose_name_plural = "ParaHumans"

    def __unicode__(self):
        return self.cape_name


class Entrance(models.Model):

    title = models.CharField(max_length=200)
    text = models.TextField()
    parahumans = models.ManyToManyField(ParaHuman, related_name='entrances')

wiki/views.py
from django.views import generic
from .models import ParaHuman, Entrance

# Create your views here.


class IndexView(generic.ListView):
    model = ParaHuman
    template_name = 'index.html'
    queryset = ParaHuman.objects.all()
    template_name_suffix = 'parahuman_list'

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response, using the `response_class` for this
        view, with a template rendered with the given context.
        If any keyword arguments are provided, they will be
        passed to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        context['parahumans'] = True
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )


class ParaHumanDetailView(generic.DetailView):
    model = ParaHuman
    template_name = 'parahuman.html'

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response, using the `response_class` for this
        view, with a template rendered with the given context.
        If any keyword arguments are provided, they will be
        passed to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        context['parahumans'] = True
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )


class EntranceDetailView(generic.DetailView):
    model = Entrance
    template_name = 'entrance.html'

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response, using the `response_class` for this
        view, with a template rendered with the given context.
        If any keyword arguments are provided, they will be
        passed to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        context['entrances'] = True
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )


class EntrancesListView(generic.ListView):
    model = Entrance
    template_name = 'entrances_list.html'

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response, using the `response_class` for this
        view, with a template rendered with the given context.
        If any keyword arguments are provided, they will be
        passed to the constructor of the response class.
        """
        response_kwargs.setdefault('content_type', self.content_type)
        context['entrances'] = True
        return self.response_class(
            request=self.request,
            template=self.get_template_names(),
            context=context,
            using=self.template_engine,
            **response_kwargs
        )

wiki/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Parahumans Wiki</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item {% if parahumans %} active {% endif %}" href="{% url 'index' %}">Parahumans</a>
          <a class="blog-nav-item {% if entrances %} active {% endif %}" href="{% url 'entrances' %}">Entrances</a>
        </nav>
      </div>
    </div>

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title">Parahumans Wiki</h1>
        <p class="lead blog-description">The official wiki about parahumans all arund the world!.</p>
      </div>

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">
              {% block title %}
                
              {% endblock title %}
            </h2>
            <p class="blog-post-meta">
              {% block subtitle %}
                
              {% endblock subtitle %}
            </p>
            {% block content %}
            {% endblock content %}
            
          </div><!-- /.blog-post -->
          {% comment %}
            <nav>
              <ul class="pager">
                <li><a href="#">Previous</a></li>
                <li><a href="#">Next</a></li>
              </ul>
            </nav>
          {% endcomment %}

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>The information displayed on this page, is provided by people that claimed to be on the site of the events. By no means the developers of the page made their self responsible by the fidelity of the information here displayed.</p>
          </div>
          <div class="sidebar-module">
            <h4>
              {% block entitle %}
                
              {% endblock entitle %}
            </h4>
            <ol class="list-unstyled">
              {% block entrances %}
                
              {% endblock entrances %}
            </ol>
          </div>
          <div class="sidebar-module">
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Parahumans wiki  sponsored by <a href="http://turpialdev.com">Turpial Dev</a>.</p>
      <p>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

wiki/templates/entrance.html
{% extends "base.html" %}
{% block title %}
	{{entrance.title}}
{% endblock title %}
{% block entitle %}
	Parahumans
{% endblock entitle %}
{% block entrances %}
	
	{% for parahuman in entrance.parahumans.all %}
		<li>
			<a href="{% url 'parahuman' parahuman.pk %}">
				{{parahuman.cape_name}}
			</a>
		</li>
	{% endfor %}

{% endblock entrances %}
{% block content %}
	<p>{{entrance.text}}</p>	
{% endblock content %}

wiki/templates/entrances_list.html
{% extends "base.html" %}
{% block title %}
	Entrances	
{% endblock title %}
{% block subtitle %}
	Recent events
{% endblock subtitle %}
{% block content %}
	{% for entrance in entrance_list %}
		<li>
			<a href="{% url 'entrance' entrance.pk %}">
				{{entrance.title}}
			</a>
		</li>
	{% endfor %}
{% endblock content %}

wiki/templates/index.html
{% extends "base.html" %}
{% block title %}
Parahumans	
{% endblock title %}
{% block subtitle %}
	List of known parahumans
{% endblock subtitle %}
{% block content %}
{% for parahuman in parahuman_list %}
	
	<li><a href="{%url 'parahuman' parahuman.pk %}">{{parahuman.cape_name}}</a></li>

{% endfor %}	
{% endblock content %}

wiki/templates/parahuman.html
{% extends "base.html" %}
{% block title %}
<h1>{{parahuman.cape_name}}</h1>	
{% endblock title %}
{% block content %}
<p>{{parahuman.description}}</p>	
{% endblock content %}

{% block entitle %}
	Entrances
{% endblock entitle %}
{% block entrances %}
	{% for entrance in parahuman.entrances.all %}
		<li><a href="{% url 'entrance' entrance.pk %}">{{entrance.title}}</a></li>
	{% endfor %}	
{% endblock entrances %}